dataset:
  name: healthcare-stroke-data
  path: s3://gretel-datasets/healthcare-dataset-stroke-data.csv
  target_column: stroke
  drop_columns: id
ML:
  ml_task: classification
  objective: binary:logistic
  objective_type: Maximize
  ml_eval_metric: f1
  ml_metric_threshold: 0.0
gretel:
  strategy: balance
  generate_factor: 1.0
  target_balance: 1.0
